package edu.ncsu.csc326.wolfcafe.controller;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;

import edu.ncsu.csc326.wolfcafe.dto.InventoryDto;
import edu.ncsu.csc326.wolfcafe.dto.RecipeDto;
import edu.ncsu.csc326.wolfcafe.service.InventoryService;
import edu.ncsu.csc326.wolfcafe.service.RecipeService;
import jakarta.persistence.EntityManager;

/**
 * Tests for MakeRecipeController covering UC6 Order Beverage functionality.
 *
 *
 * GENERATIVE AI WAS USED
 *
 * GPT 4.1 was used to modify existing code in this file. The following prompts were used:
 *
 * - "Create a new test class MakeRecipeControllerTest.java to test the MakeRecipeController."
 * - "Add test methods to MakeRecipeControllerTest.java to cover main flow and alternative flows for UC6 Order Beverage."
 * - "Ensure the tests in MakeRecipeControllerTest.java use MockMvc to simulate HTTP requests and validate responses."
 * - "Add setup method in MakeRecipeControllerTest.java to clean database tables before each test."
 * - "Make sure the tests in MakeRecipeControllerTest.java are transactional to rollback changes after each test."
 *
 * The code generated by the AI was reviewed and adjusted as necessary by the author to ensure correctness and completeness.
 *
 * @author Dania Swelam
 */
@SpringBootTest
@AutoConfigureMockMvc
class MakeRecipeControllerTest {

    /** Mock MVC for testing controller endpoints */
    @Autowired
    private MockMvc          mvc;

    /** Reference to InventoryService for setup */
    @Autowired
    private InventoryService inventoryService;

    /** Reference to RecipeService for setup */
    @Autowired
    private RecipeService    recipeService;

    /** Reference to EntityManager for cleanup */
    @Autowired
    private EntityManager    entityManager;

    /**
     * Sets up the test case by cleaning database tables.
     */
    @BeforeEach
    public void setUp () throws Exception {
        // Clean up all tables in proper order due to foreign key constraints
        try {
            entityManager.createNativeQuery( "DELETE FROM inventory_ingredients" ).executeUpdate();
        }
        catch ( final Exception e ) {
            // Table might not exist yet, ignore
        }
        try {
            entityManager.createNativeQuery( "DELETE FROM recipe_ingredients" ).executeUpdate();
        }
        catch ( final Exception e ) {
            // Table might not exist yet, ignore
        }
        try {
            entityManager.createNativeQuery( "DELETE FROM inventory" ).executeUpdate();
        }
        catch ( final Exception e ) {
            // Table might not exist yet, ignore
        }
        try {
            entityManager.createNativeQuery( "DELETE FROM recipe" ).executeUpdate();
        }
        catch ( final Exception e ) {
            // Table might not exist yet, ignore
        }
        try {
            entityManager.createNativeQuery( "ALTER TABLE inventory AUTO_INCREMENT = 1" ).executeUpdate();
        }
        catch ( final Exception e ) {
            // Table might not exist yet, ignore
        }
        try {
            entityManager.createNativeQuery( "ALTER TABLE recipe AUTO_INCREMENT = 1" ).executeUpdate();
        }
        catch ( final Exception e ) {
            // Table might not exist yet, ignore
        }
    }

    /**
     * Test successful recipe making with exact payment - Main Flow.
     */
    @Test
    @Transactional
    @WithMockUser ( roles = { "CUSTOMER" } )
    void testMakeRecipeSuccessExactPayment () throws Exception {
        // Set up inventory with sufficient ingredients
        final Map<String, Integer> inventoryIngredients = new HashMap<>();
        inventoryIngredients.put( "Coffee", 15 );
        inventoryIngredients.put( "Milk", 10 );
        inventoryIngredients.put( "Sugar", 8 );
        inventoryIngredients.put( "Chocolate", 5 );
        final InventoryDto inventoryDto = new InventoryDto( inventoryIngredients );
        inventoryService.createInventory( inventoryDto );

        // Set up recipe
        final Map<String, Integer> recipeIngredients = new HashMap<>();
        recipeIngredients.put( "Coffee", 3 );
        recipeIngredients.put( "Milk", 1 );
        recipeIngredients.put( "Sugar", 2 );
        final RecipeDto recipeDto = new RecipeDto();
        recipeDto.setName( "Latte" );
        recipeDto.setPrice( 75 );
        recipeDto.setIngredients( recipeIngredients );
        recipeService.createRecipe( recipeDto );

        // Test successful order with exact payment (change should be 0)
        mvc.perform( post( "/api/makerecipe/Latte" ).contentType( MediaType.APPLICATION_JSON ).content( "75" ) )
                .andExpect( status().isOk() ).andExpect( content().string( "0" ) );
    }

    /**
     * Test successful recipe making with overpayment - Main Flow.
     */
    @Test
    @Transactional
    @WithMockUser ( roles = { "CUSTOMER" } )
    void testMakeRecipeSuccessWithChange () throws Exception {
        // Set up inventory with sufficient ingredients
        final Map<String, Integer> inventoryIngredients = new HashMap<>();
        inventoryIngredients.put( "Coffee", 15 );
        inventoryIngredients.put( "Milk", 10 );
        inventoryIngredients.put( "Sugar", 8 );
        final InventoryDto inventoryDto = new InventoryDto( inventoryIngredients );
        inventoryService.createInventory( inventoryDto );

        // Set up recipe
        final Map<String, Integer> recipeIngredients = new HashMap<>();
        recipeIngredients.put( "Coffee", 2 );
        recipeIngredients.put( "Milk", 1 );
        final RecipeDto recipeDto = new RecipeDto();
        recipeDto.setName( "Simple Coffee" );
        recipeDto.setPrice( 50 );
        recipeDto.setIngredients( recipeIngredients );
        recipeService.createRecipe( recipeDto );

        // Test successful order with overpayment (change should be 25)
        mvc.perform( post( "/api/makerecipe/Simple Coffee" ).contentType( MediaType.APPLICATION_JSON ).content( "75" ) )
                .andExpect( status().isOk() ).andExpect( content().string( "25" ) );
    }

    /**
     * Test insufficient payment alternative flow.
     */
    @Test
    @Transactional
    @WithMockUser ( roles = { "CUSTOMER" } )
    void testMakeRecipeInsufficientPayment () throws Exception {
        // Set up inventory with sufficient ingredients
        final Map<String, Integer> inventoryIngredients = new HashMap<>();
        inventoryIngredients.put( "Coffee", 15 );
        inventoryIngredients.put( "Milk", 10 );
        final InventoryDto inventoryDto = new InventoryDto( inventoryIngredients );
        inventoryService.createInventory( inventoryDto );

        // Set up expensive recipe
        final Map<String, Integer> recipeIngredients = new HashMap<>();
        recipeIngredients.put( "Coffee", 2 );
        final RecipeDto recipeDto = new RecipeDto();
        recipeDto.setName( "Expensive Coffee" );
        recipeDto.setPrice( 100 );
        recipeDto.setIngredients( recipeIngredients );
        recipeService.createRecipe( recipeDto );

        // Test insufficient payment - should return HTTP 409 CONFLICT and error
        // message
        mvc.perform(
                post( "/api/makerecipe/Expensive Coffee" ).contentType( MediaType.APPLICATION_JSON ).content( "50" ) )
                .andExpect( status().isConflict() )
                .andExpect( content().string( "Insufficient funds to pay. Your money has been returned." ) );
    }

    /**
     * Test insufficient ingredients alternative flow.
     */
    @Test
    @Transactional
    @WithMockUser ( roles = { "CUSTOMER" } )
    void testMakeRecipeInsufficientIngredients () throws Exception {
        // Set up inventory with insufficient ingredients
        final Map<String, Integer> inventoryIngredients = new HashMap<>();
        inventoryIngredients.put( "Coffee", 1 );
        inventoryIngredients.put( "Milk", 1 );
        final InventoryDto inventoryDto = new InventoryDto( inventoryIngredients );
        inventoryService.createInventory( inventoryDto );

        // Set up recipe requiring more ingredients than available
        final Map<String, Integer> recipeIngredients = new HashMap<>();
        recipeIngredients.put( "Coffee", 5 );
        recipeIngredients.put( "Milk", 3 );
        final RecipeDto recipeDto = new RecipeDto();
        recipeDto.setName( "Large Latte" );
        recipeDto.setPrice( 50 );
        recipeDto.setIngredients( recipeIngredients );
        recipeService.createRecipe( recipeDto );

        // Test insufficient ingredients - should return HTTP 400 BAD_REQUEST
        // and error message
        mvc.perform( post( "/api/makerecipe/Large Latte" ).contentType( MediaType.APPLICATION_JSON ).content( "75" ) )
                .andExpect( status().isBadRequest() ).andExpect(
                        content().string( "Insufficient inventory to make beverage. Your money has been returned." ) );
    }

    /**
     * Test recipe not found alternative flow.
     */
    @Test
    @Transactional
    @WithMockUser ( roles = { "CUSTOMER" } )
    void testMakeRecipeRecipeNotFound () throws Exception {
        // Set up inventory (not used in this test but needed for service)
        final Map<String, Integer> inventoryIngredients = new HashMap<>();
        inventoryIngredients.put( "Coffee", 15 );
        final InventoryDto inventoryDto = new InventoryDto( inventoryIngredients );
        inventoryService.createInventory( inventoryDto );

        // Test with non-existent recipe name - should return HTTP 404 NOT_FOUND
        // and error message
        mvc.perform( post( "/api/makerecipe/NonExistent Recipe" ).contentType( MediaType.APPLICATION_JSON )
                .content( "100" ) ).andExpect( status().isNotFound() )
                .andExpect( content().string( "Recipe not found." ) );
    }

    /**
     * Test with invalid JSON payload.
     */
    @Test
    @Transactional
    @WithMockUser ( roles = { "CUSTOMER" } )
    void testMakeRecipeInvalidPayload () throws Exception {
        // Set up inventory
        final Map<String, Integer> inventoryIngredients = new HashMap<>();
        inventoryIngredients.put( "Coffee", 15 );
        final InventoryDto inventoryDto = new InventoryDto( inventoryIngredients );
        inventoryService.createInventory( inventoryDto );

        // Set up recipe
        final Map<String, Integer> recipeIngredients = new HashMap<>();
        recipeIngredients.put( "Coffee", 2 );
        final RecipeDto recipeDto = new RecipeDto();
        recipeDto.setName( "Test Coffee" );
        recipeDto.setPrice( 50 );
        recipeDto.setIngredients( recipeIngredients );
        recipeService.createRecipe( recipeDto );

        // Test with invalid JSON payload - should return HTTP 400 BAD_REQUEST
        mvc.perform( post( "/api/makerecipe/Test Coffee" ).contentType( MediaType.APPLICATION_JSON )
                .content( "invalid-json" ) ).andExpect( status().isBadRequest() );
    }

    /**
     * Test with missing request body.
     */
    @Test
    @Transactional
    @WithMockUser ( roles = { "CUSTOMER" } )
    void testMakeRecipeMissingBody () throws Exception {
        // Set up inventory
        final Map<String, Integer> inventoryIngredients = new HashMap<>();
        inventoryIngredients.put( "Coffee", 15 );
        final InventoryDto inventoryDto = new InventoryDto( inventoryIngredients );
        inventoryService.createInventory( inventoryDto );

        // Set up recipe
        final Map<String, Integer> recipeIngredients = new HashMap<>();
        recipeIngredients.put( "Coffee", 2 );
        final RecipeDto recipeDto = new RecipeDto();
        recipeDto.setName( "Test Coffee" );
        recipeDto.setPrice( 50 );
        recipeDto.setIngredients( recipeIngredients );
        recipeService.createRecipe( recipeDto );

        // Test with missing request body - should return HTTP 400 BAD_REQUEST
        mvc.perform( post( "/api/makerecipe/Test Coffee" ).contentType( MediaType.APPLICATION_JSON ) )
                .andExpect( status().isBadRequest() );
    }

    /**
     * Test with negative payment amount.
     */
    @Test
    @Transactional
    @WithMockUser ( roles = { "CUSTOMER" } )
    void testMakeRecipeNegativePayment () throws Exception {
        // Set up inventory
        final Map<String, Integer> inventoryIngredients = new HashMap<>();
        inventoryIngredients.put( "Coffee", 15 );
        final InventoryDto inventoryDto = new InventoryDto( inventoryIngredients );
        inventoryService.createInventory( inventoryDto );

        // Set up recipe
        final Map<String, Integer> recipeIngredients = new HashMap<>();
        recipeIngredients.put( "Coffee", 2 );
        final RecipeDto recipeDto = new RecipeDto();
        recipeDto.setName( "Test Coffee" );
        recipeDto.setPrice( 50 );
        recipeDto.setIngredients( recipeIngredients );
        recipeService.createRecipe( recipeDto );

        // Test with negative payment - should return HTTP 409 CONFLICT and
        // error message
        mvc.perform( post( "/api/makerecipe/Test Coffee" ).contentType( MediaType.APPLICATION_JSON ).content( "-10" ) )
                .andExpect( status().isConflict() )
                .andExpect( content().string( "Insufficient funds to pay. Your money has been returned." ) );
    }

}
